/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package compiler.ast.syntactic;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int MULTICOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\53\1\50\1\17"+
    "\2\0\1\46\1\42\1\20\1\27\1\30\1\16\1\45\1\32\1\10"+
    "\1\51\1\4\1\12\7\54\2\11\1\0\1\31\1\43\1\33\1\44"+
    "\2\0\6\15\21\5\1\13\2\5\1\36\1\52\1\37\1\41\1\7"+
    "\1\0\1\21\1\26\1\15\1\15\1\15\1\25\1\5\1\5\1\5"+
    "\1\5\1\5\1\5\1\5\1\23\1\5\2\5\1\22\1\5\1\24"+
    "\1\5\1\6\1\5\1\14\1\5\1\5\1\34\1\40\1\35\1\47"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\3\1"+
    "\3\37\1\0\1\40\1\41\1\42\1\43\1\44\1\0"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\0\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\77\1\100\14\0\1\101\1\102"+
    "\1\103\1\104\1\105\1\66\1\106\1\107\1\0\1\110"+
    "\1\0\1\111\1\112\1\113\1\114\1\115\1\116\1\117"+
    "\1\120\1\121\1\66\1\106\2\0\1\122";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\264\0\341\0\u010e"+
    "\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\u021c\0\264\0\264\0\264\0\264"+
    "\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\264"+
    "\0\u0384\0\264\0\u03b1\0\264\0\u03de\0\u040b\0\u0438\0\264"+
    "\0\u0465\0\u0492\0\u04bf\0\264\0\264\0\264\0\264\0\264"+
    "\0\u04ec\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\u0519\0\264\0\u0546\0\264\0\264\0\264"+
    "\0\264\0\264\0\u0573\0\u05a0\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\u05cd\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\264\0\264\0\u04ec\0\264\0\264\0\u07e9"+
    "\0\u0816\0\264\0\u0843\0\264\0\u0870\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\u089d\0\u08ca\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\6\1\10\2\11\1\5\1\12"+
    "\1\13\1\14\3\11\1\15\1\16\1\17\6\11\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\2\5\1\13\1\43\2\5\14\43\1\44"+
    "\32\43\1\45\2\43\1\46\2\5\15\46\1\5\31\46"+
    "\1\47\2\46\4\50\1\51\11\50\1\52\36\50\56\0"+
    "\1\6\57\0\1\53\11\0\1\54\14\0\1\55\26\0"+
    "\3\11\1\0\5\11\3\0\6\11\25\0\1\11\10\0"+
    "\1\56\1\13\1\14\20\0\1\57\10\0\1\60\7\0"+
    "\1\13\11\0\2\13\41\0\1\13\11\0\2\13\2\61"+
    "\37\0\1\13\4\0\1\62\26\0\1\63\54\0\1\64"+
    "\54\0\1\65\4\0\1\66\47\0\1\67\54\0\1\70"+
    "\6\0\1\71\45\0\1\72\7\0\1\73\44\0\1\74"+
    "\10\0\1\75\43\0\1\76\11\0\1\77\42\0\1\100"+
    "\54\0\1\101\21\0\1\43\2\0\14\43\1\0\32\43"+
    "\1\0\2\43\6\0\1\102\3\0\1\103\1\0\1\104"+
    "\2\0\1\105\1\106\1\107\1\110\1\111\1\112\1\113"+
    "\1\114\24\0\1\115\1\103\20\0\1\116\42\0\1\117"+
    "\3\0\1\120\1\0\1\121\2\0\1\122\1\123\1\124"+
    "\1\125\1\126\1\127\1\130\1\131\23\0\1\132\1\0"+
    "\1\120\16\0\1\133\42\0\1\134\50\0\1\53\1\6"+
    "\1\7\52\53\11\0\2\135\2\0\1\135\3\0\1\135"+
    "\3\0\2\135\25\0\1\135\33\0\1\136\54\0\1\137"+
    "\33\0\1\140\41\0\1\140\11\0\2\141\2\0\1\141"+
    "\3\0\1\141\3\0\2\141\25\0\1\141\20\0\1\142"+
    "\46\0\1\143\5\0\1\144\33\0\1\143\11\0\2\145"+
    "\2\0\1\145\3\0\1\145\3\0\2\145\25\0\1\145"+
    "\20\0\1\146\54\0\1\147\54\0\1\150\54\0\1\151"+
    "\54\0\1\152\54\0\1\153\54\0\1\154\54\0\1\155"+
    "\54\0\1\156\46\0\1\157\41\0\1\157\11\0\2\160"+
    "\2\0\1\160\3\0\1\160\3\0\2\160\25\0\1\160"+
    "\12\0\1\161\5\0\1\144\33\0\1\161\11\0\2\162"+
    "\2\0\1\162\2\0\1\163\1\162\3\0\2\162\25\0"+
    "\1\162\20\0\1\144\54\0\1\163\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2295];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\7\1\6\11\1\1\4\11\7\1\1\11"+
    "\1\1\1\11\1\1\1\11\3\1\1\11\2\1\1\0"+
    "\5\11\1\0\11\11\1\1\1\11\1\1\5\11\1\1"+
    "\1\0\12\11\14\0\2\11\1\1\2\11\2\1\1\11"+
    "\1\0\1\11\1\0\13\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private int CommentCount = 0;

    StringBuffer string = new StrngBuffer();

    private void err(String message) throws RuntimeException {
        throw new RuntimeException(message + "Scanning error in the line" + yyline + ",
        column" + yycolumn + ": ");
    }

    private Symbol tok (int type){
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol tok (int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { err("Illegal character" + yytext());
          }
        case 83: break;
        case 2: 
          { /* skip */
          }
        case 84: break;
        case 3: 
          { return tok(DIV);
          }
        case 85: break;
        case 4: 
          { return tok(IDENTIFIER, yytext());
          }
        case 86: break;
        case 5: 
          { return tok(MINUS);
          }
        case 87: break;
        case 6: 
          { return tok(INTEGER), new Integer(yytext());
          }
        case 88: break;
        case 7: 
          { return tok(ASTERISH);
          }
        case 89: break;
        case 8: 
          { string.setLength(0); yybegin{STRING};
          }
        case 90: break;
        case 9: 
          { string.setLength(0); yybegin{CHAR};
          }
        case 91: break;
        case 10: 
          { return tok(LPAREN);
          }
        case 92: break;
        case 11: 
          { return tok(RPAREN);
          }
        case 93: break;
        case 12: 
          { return tok(SEMICOLON);
          }
        case 94: break;
        case 13: 
          { return tok(COMMA);
          }
        case 95: break;
        case 14: 
          { return tok(ASSIGN);
          }
        case 96: break;
        case 15: 
          { return tok(LBRACE);
          }
        case 97: break;
        case 16: 
          { return tok(RBRACE);
          }
        case 98: break;
        case 17: 
          { return tok(LBRACKET);
          }
        case 99: break;
        case 18: 
          { return tok(RBRACKET);
          }
        case 100: break;
        case 19: 
          { return tok(VBAR);
          }
        case 101: break;
        case 20: 
          { return tok(CARET);
          }
        case 102: break;
        case 21: 
          { return tok(AMPERS);
          }
        case 103: break;
        case 22: 
          { return tok(LT);
          }
        case 104: break;
        case 23: 
          { return tok(GT);
          }
        case 105: break;
        case 24: 
          { return tok(PLUS);
          }
        case 106: break;
        case 25: 
          { return tok(MOD);
          }
        case 107: break;
        case 26: 
          { return tok(TILDE);
          }
        case 108: break;
        case 27: 
          { return tok(EXCLAM);
          }
        case 109: break;
        case 28: 
          { return tok(DOT);
          }
        case 110: break;
        case 29: 
          { string.append(yytext());
          }
        case 111: break;
        case 30: 
          { yybegin{YYINITIAL};
                              return tok(STRING_LITERAL,
                              string.toString());
          }
        case 112: break;
        case 31: 
          { 
          }
        case 113: break;
        case 32: 
          { CommentCount = 1; yybegin(MULTICOMMENT);
          }
        case 114: break;
        case 33: 
          { return tok(DIV_ASSIGN);
          }
        case 115: break;
        case 34: 
          { return tok(DEC);
          }
        case 116: break;
        case 35: 
          { return tok(SUB_ASSIGN);
          }
        case 117: break;
        case 36: 
          { return tok(PTR);
          }
        case 118: break;
        case 37: 
          { err("comment symbol do not match!");
          }
        case 119: break;
        case 38: 
          { return tok(MUL_ASSIGN);
          }
        case 120: break;
        case 39: 
          { return tok(EQ);
          }
        case 121: break;
        case 40: 
          { return tok(OR_ASSIGN);
          }
        case 122: break;
        case 41: 
          { return tok(OR);
          }
        case 123: break;
        case 42: 
          { return tok(XOR_ASSIGN);
          }
        case 124: break;
        case 43: 
          { return tok(AND_ASSIGN);
          }
        case 125: break;
        case 44: 
          { return tok(AND);
          }
        case 126: break;
        case 45: 
          { return tok(LE);
          }
        case 127: break;
        case 46: 
          { return tok(SHL);
          }
        case 128: break;
        case 47: 
          { return tok(GE);
          }
        case 129: break;
        case 48: 
          { return tok(SHR);
          }
        case 130: break;
        case 49: 
          { return tok(PLUS_ASSIGN);
          }
        case 131: break;
        case 50: 
          { return tok(INC);
          }
        case 132: break;
        case 51: 
          { return tok(MOD_ASSIGN);
          }
        case 133: break;
        case 52: 
          { return tok(NE);
          }
        case 134: break;
        case 53: 
          { string.append('\v');
          }
        case 135: break;
        case 54: 
          { string.append((char) Integer.valueOf(yytext().subString(1, yytext().length()), 8).intValue());
          }
        case 136: break;
        case 55: 
          { string.append('\"');
          }
        case 137: break;
        case 56: 
          { string.append('\'');
          }
        case 138: break;
        case 57: 
          { string.append('\a');
          }
        case 139: break;
        case 58: 
          { string.append('\r');
          }
        case 140: break;
        case 59: 
          { string.append ('\n');
          }
        case 141: break;
        case 60: 
          { string.append('\t');
          }
        case 142: break;
        case 61: 
          { string.append('\f');
          }
        case 143: break;
        case 62: 
          { string.append('\b');
          }
        case 144: break;
        case 63: 
          { string.append('\\');
          }
        case 145: break;
        case 64: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL,
                              yytext().charAt(0));
          }
        case 146: break;
        case 65: 
          { CommentCount++;
          }
        case 147: break;
        case 66: 
          { CommentCount--;
                      if (CommentCount == 0) yybegin(YYINITIAL);
          }
        case 148: break;
        case 67: 
          { return tok(INTEGER),
                              new Integer(valueOf(yyetext(), 16));
          }
        case 149: break;
        case 68: 
          { return tok(SHL_ASSIGN);
          }
        case 150: break;
        case 69: 
          { return tok(SHR_ASSIGN);
          }
        case 151: break;
        case 70: 
          { string.append((char) Integer.valueOf(yytext().subString(2, yytext().length()), 16).intValue());
          }
        case 152: break;
        case 71: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\v');
          }
        case 153: break;
        case 72: 
          { yybegin{YYINITIAL};
                              return tok(CHAR_LITERAL,
                              (char) Integer.valueOf(yytext().subString(1, yytext().length() - 1), 8).intValue());
          }
        case 154: break;
        case 73: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\"');
          }
        case 155: break;
        case 74: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\'');
          }
        case 156: break;
        case 75: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\a');
          }
        case 157: break;
        case 76: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\r');
          }
        case 158: break;
        case 77: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\n');
          }
        case 159: break;
        case 78: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\t');
          }
        case 160: break;
        case 79: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\f');
          }
        case 161: break;
        case 80: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\b');
          }
        case 162: break;
        case 81: 
          { yybegin(YYINITIAL);
                              return tok(CHAR_LITERAL, '\\');
          }
        case 163: break;
        case 82: 
          { yybegin{YYINITIAL};
                              return tok(CHAR_LITERAL,
                              (char) Integer.valueOf(yytext().subString(2, yytext().length() - 1), 16).intValue());
          }
        case 164: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     if (yystate() ==  MULTICOMMENT)
        err("Comment symbol do not match (EOF)!");
    return tok(EOF, null);
    }
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
