
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 22 19:49:55 CST 2015
//----------------------------------------------------

package compiler.PrettyPrinter;

/** CUP generated interface containing symbol constants. */
public interface prettySym {
  /* terminals */
  public static final int SHR_ASSIGN = 53;
  public static final int SHR = 44;
  public static final int STRING_LITERAL = 59;
  public static final int XOR_ASSIGN = 55;
  public static final int LBRACKET = 22;
  public static final int SHL = 43;
  public static final int CHAR = 3;
  public static final int CHAR_LITERAL = 61;
  public static final int GE = 42;
  public static final int PLUS_ASSIGN = 57;
  public static final int DECINTEGER = 60;
  public static final int OCTINTEGER = 62;
  public static final int HEXINTEGER = 63;
  public static final int EXCLAM = 35;
  public static final int LPAREN = 15;
  public static final int CONTINUE = 11;
  public static final int INT = 4;
  public static final int FOR = 10;
  public static final int MINUS = 30;
  public static final int TILDE = 34;
  public static final int RPAREN = 16;
  public static final int SUB_ASSIGN = 51;
  public static final int AND = 38;
  public static final int SEMICOLON = 17;
  public static final int SIZEOF = 14;
  public static final int LT = 27;
  public static final int OR = 37;
  public static final int COMMA = 18;
  public static final int INC = 45;
  public static final int DIV = 31;
  public static final int PLUS = 29;
  public static final int ASSIGN = 19;
  public static final int IF = 7;
  public static final int CARET = 25;
  public static final int PTR = 47;
  public static final int DOT = 36;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 23;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 52;
  public static final int VBAR = 24;
  public static final int MOD = 33;
  public static final int BREAK = 12;
  public static final int VOID = 2;
  public static final int EQ = 39;
  public static final int MOD_ASSIGN = 50;
  public static final int DIV_ASSIGN = 49;
  public static final int AMPERS = 26;
  public static final int UNION = 6;
  public static final int LBRACE = 20;
  public static final int ELSE = 8;
  public static final int AND_ASSIGN = 54;
  public static final int WHILE = 9;
  public static final int OR_ASSIGN = 56;
  public static final int RBRACE = 21;
  public static final int NE = 40;
  public static final int MULTI = 32;
  public static final int MUL_ASSIGN = 48;
  public static final int DEC = 46;
  public static final int STRUCT = 5;
  public static final int GT = 28;
  public static final int IDENTIFIER = 58;
  public static final int COMMENT = 100;
  public static final int INCLUDE = 101;
}

